export const REQUEST_PRODUCTS = "REQUEST_PRODUCTS";
export const REQUEST_SUCCESS_PRODUCTS = "REQUEST_SUCCESS_PRODUCTS";
export const REQUEST_FAIL_PRODUCTS = "REQUEST_FAIL_PRODUCTS";

export const ADD_CART = "ADD_CART";
export const REMOVE_CART = "REMOVE_CART";
export const REMOVE_ITEM_CART = "REMOVE_ITEM_CART";
export const REMOVE_ALL_CART = "REMOVE_ALL_CART";
